- hosts: all
  become: yes
  tasks: 
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: latest
        
    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Create users 
      ansible.builtin.user:
        name: "{{ item }}"
      loop:  
          - jenny
          - rose
          - jisoo
          - lisa
     